
#General Config Section
[general]
	#The Client ID of the Discord App to use
	clientID = 908792720972202045
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 12

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Loading Sky to Void"
	#The second line of text under the app name
	state = "Preparing to cross the Void."
	#The Asset ID of the image to display as the large image
	largeImageKey = "stvmainlogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Sky to Void Adventure Modpack, %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "stvsimplelogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Playing Sky to Void Modpack"
	#The seconds line of text under the app name
	state = "Admiring the splash menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "stvmainlogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Sky to Void Adventure Modpack, %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "stvsimplelogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Playing Sky to Void Modpack"
	#The second line of text under the app name
	state = "%player% is looking for a server"
	#The Asset ID of the image to display as the large image
	largeImageKey = "stvmainlogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Sky to Void Adventure Modpack, %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "stvsimplelogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing Sky to Void Modpack"
	#The second line of text under the app name
	state = "Beginning their journey.."
	#The Asset ID of the image to display as the large image
	largeImageKey = "stvmainlogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Sky to Void Adventure Modpack, %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "stvsimplelogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing Sky to Void Modpack"
	#The second line of text under the app name
	state = "Taking revenge against the gods!"
	#The Asset ID of the image to display as the large image
	largeImageKey = "stvmainlogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Sky to Void Adventure Modpack, %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "stvsimplelogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing Sky to Void Modpack"
	#The second line of text under the app name
	state = "Building The Obelisk with %players% friends!"
	#The Asset ID of the image to display as the large image
	largeImageKey = "stvmainlogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Sky to Void Adventure Modpack, %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "stvsimplelogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing Sky to Void"
	#The second line of text under the app name
	state = "Trying to escape the apocalypse"
	#The Asset ID of the image to display as the large image
	largeImageKey = "stvmainlogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Sky to Void Adventure Modpack, %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "stvsimplelogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

